openapi: 3.0.0
info:
  title: ROS Client API
  version: '1.0'
servers:
  - url: 'http://localhost:5000'
    description: Dev
paths:
  /update:
    get:
      summary: Returns the update-data
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodes:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        running:
                          type: boolean
                      required:
                        - name
                        - running
                  topics:
                    type: array
                    items:
                      $ref: '#/components/schemas/Topic'
                required:
                  - nodes
                  - topics
      operationId: get-update
      description: ''
  '/nodes/toggle/{package}/{node}':
    parameters:
      - schema:
          type: string
        name: package
        in: path
        required: true
      - schema:
          type: string
        name: node
        in: path
        required: true
    patch:
      summary: Toggles the given node running-status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
                description: The new status of the node
      operationId: get-nodes-toggle-package-node
  '/topics/update':
    get:
      summary: Returns the update for the topics
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic'
      operationId: get-topics-update
components:
  schemas:
    Topic:
      title: Topic
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          example: generic
        content:
          type: array
          items:
            type: string
      required:
        - name
        - type
        - content